language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - extra-google-m2repository
    - extra-android-m2repository
    - android-23
    - sys-img-x86-android-18
