language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-28
# Support library
    - extra-android-support
    - extra-android-m2repository

before_script:
    - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew assembleDebug assembleRelease
   - ./gradlew checkstyle
   - ./gradlew test
