files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        pt-PT: pt-rPT
        zh-CN: zh-rCN
        en-AU: en-rAU
        en-GB: en-rGB
        nl-BE: nl-rBE
        nl: nl
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
        
  - source: /app/src/obf/res/values/strings.xml
    translation: /app/src/obf/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        pt-BR: pt-rBR
        en-AU: en-rAU
        pt-PT: pt-rPT
        nl-BE: nl-rBE
        nl: nl
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        sr-CS: sr
        sr: rs
        
  - source: /app/src/off/res/values/strings.xml
    translation: /app/src/off/res/values-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-HK: zh-rHK
        zh-TW: zh-rTW
        sr-CS: sr
        sr: rs
        
  - source: /app/src/opff/res/values/strings.xml
    translation: /app/src/opff/res/values-%two_letters_code%/strings.xml
    languages_mapping:
      two_letters_code:
        zh-CN: zh-rCN
        en-GB: en-rGB
        en-AU: en-rAU
        pt-BR: pt-rBR
        nl-BE: nl-rBE
        pt-PT: pt-rPT
        zh-TW: zh-rTW
        zh-HK: zh-rHK
        sr-CS: sr
        sr: rs
